[package]
name = "fuzzyplot"
version = "0.1.1"
authors = ["Autumn! <autumnull@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
num = "0.3.1"
image = "0.23.14"
anyhow = "1.0.42"
